- fix compile error
system.cc:273:1: error: narrowing conversion of ‘33024’ from ‘ushort’ {aka ‘short unsigned int’} to ‘short int’ inside { } [-Wnarrowing]
 };
 ^
system.cc:273:1: error: narrowing conversion of ‘32768’ from ‘ushort’ {aka ‘short unsigned int’} to ‘short int’ inside { } [-Wnarrowing]
system.cc:273:1: error: narrowing conversion of ‘33792’ from ‘ushort’ {aka ‘short unsigned int’} to ‘short int’ inside { } [-Wnarrowing]
system.cc:273:1: error: narrowing conversion of ‘33792’ from ‘ushort’ {aka ‘short unsigned int’} to ‘short int’ inside { } [-Wnarrowing]

Use unsigned short instead short because some key codes consts are exciding 0x8000
and looks like negative key code values are not used in any operations